source "http://rubygems.org"

gem "allure-cucumber", "2.13.8"
gem "cucumber", "~> 5.3"
gem "capybara", "~> 3.35", ">= 3.35.3"
gem "selenium-webdriver", "~> 3.142", ">= 3.142.7"
gem "rspec", "3.10"
gem "mongo", "2.13.1"
gem "httparty", "0.18.1"
