pipeline {
    agent {
        docker{
            image '00rion/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation'){
            steps {
                sh 'cd web && bundle install'
            }
        }
        
        stage('Testing') {
            steps {
                sh 'cd web && rake local_seeds'
            }
        }
        stage('UAT'){
            steps{
                echo 'Aguardando testes de aceitação.'
                input message: 'Prosseguir para produção?'
            }
        }
        stage('Prod'){
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'web/logs']]
            }
        }
    }
    post {
        always{
            echo 'todo'
        }
    }
}
