require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(password)
  return Digest::MD5.hexdigest(password)
end

task :teste do
  puts "Executando uma tarefa de teste"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
  users = [
    { name: "Alan CadAnun", email: "alanCA@temp.vc", password: to_md5("pwd123") },
    { name: "Alan Log", email: "alan_log@temp.vc", password: to_md5("pwd123") },
    { name: "Alan RmvAnun", email: "alanRA@temp.vc", password: to_md5("pwd123") },
    { name: "Joao Anunciante", email: "anunciante@temp.vc", password: to_md5("pwd123") },
    { name: "Maria Locataria", email: "locataria@temp.vc", password: to_md5("pwd123") },
  ]
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber -p jenkins"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))
  users = [
    { name: "Alan CadAnun", email: "alanCA@temp.vc", password: to_md5("pwd123") },
    { name: "Alan Log", email: "alan_log@temp.vc", password: to_md5("pwd123") },
    { name: "Alan RmvAnun", email: "alanRA@temp.vc", password: to_md5("pwd123") },
    { name: "Joao Anunciante", email: "anunciante@temp.vc", password: to_md5("pwd123") },
    { name: "Maria Locataria", email: "locataria@temp.vc", password: to_md5("pwd123") },
  ]
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)
end
